/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laundry;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.print.*;
import javax.print.attribute.*;
import javax.print.attribute.standard.*;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import static laundry.koneksi.getConnection;

/**
 *
 * @author Dzulkarnain Inc
 */
public class transaksi extends javax.swing.JFrame {

    koneksi db = new koneksi();
    Connection conn = getConnection();
    String cari = "";
    String brt = "";
    String total = "";
    String sumtotal = null;
    int hargatotal;
    
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        setLocationRelativeTo(null);
        tableload(jTable1);
        kodeload(txnotransaksi);
        idpelanggan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        search = new javax.swing.JButton();
        cbsearch = new javax.swing.JComboBox();
        txsearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txidjenis = new javax.swing.JTextField();
        txnotransaksi = new javax.swing.JTextField();
        txidpegawai = new javax.swing.JTextField();
        txidpelanggan = new javax.swing.JTextField();
        txkembali = new javax.swing.JTextField();
        txbayar = new javax.swing.JTextField();
        txtotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        printpdf = new javax.swing.JButton();
        txtanggal = new javax.swing.JTextField();
        cbberat = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Transaksi - JossLaundry");
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 40)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Data Transaksi");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(166, 228, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 2));

        jTable1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Transaksi", "ID Pegawai", "ID Pelanggan", "ID Jenis", "Tanggal", "Berat", "Harga Total", "Pembayaran", "Kembalian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(51, 102, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jTextPane1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(jTextPane1);

        search.setBackground(new java.awt.Color(0, 153, 255));
        search.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        cbsearch.setBackground(new java.awt.Color(0, 153, 255));
        cbsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        cbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Transaksi", "ID Pegawai", "ID Pelanggan", "ID Jenis" }));
        cbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsearchActionPerformed(evt);
            }
        });

        txsearch.setBackground(new java.awt.Color(213, 246, 255));
        txsearch.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel3.setText("ID Pelanggan");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setText("ID Jenis");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("No Transaksi");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel7.setText("ID Pegawai");

        txidjenis.setEditable(false);
        txidjenis.setBackground(new java.awt.Color(213, 246, 255));
        txidjenis.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txidjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidjenisActionPerformed(evt);
            }
        });

        txnotransaksi.setEditable(false);
        txnotransaksi.setBackground(new java.awt.Color(213, 246, 255));
        txnotransaksi.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txidpegawai.setBackground(new java.awt.Color(213, 246, 255));
        txidpegawai.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txidpelanggan.setEditable(false);
        txidpelanggan.setBackground(new java.awt.Color(213, 246, 255));
        txidpelanggan.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txkembali.setEditable(false);
        txkembali.setBackground(new java.awt.Color(213, 246, 255));
        txkembali.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txbayar.setBackground(new java.awt.Color(213, 246, 255));
        txbayar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        txtotal.setEditable(false);
        txtotal.setBackground(new java.awt.Color(213, 246, 255));
        txtotal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel8.setText("Total Rp.");

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel9.setText("Bayar Rp.");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel10.setText("Kembali Rp.");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Berat Cucian");

        insert.setBackground(new java.awt.Color(0, 153, 255));
        insert.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(0, 153, 255));
        update.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 153, 255));
        jButton7.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 153, 255));
        clear.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        printpdf.setBackground(new java.awt.Color(0, 153, 255));
        printpdf.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        printpdf.setText("Print");
        printpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printpdfActionPerformed(evt);
            }
        });

        txtanggal.setEditable(false);
        txtanggal.setBackground(new java.awt.Color(213, 246, 255));
        txtanggal.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        txtanggal.setText("System Date");
        txtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanggalActionPerformed(evt);
            }
        });

        cbberat.setBackground(new java.awt.Color(0, 153, 255));
        cbberat.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        cbberat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cbberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbberatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtanggal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txidjenis))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txidpelanggan))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txidpegawai))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txnotransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(printpdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton7)
                                        .addGap(1, 1, 1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbberat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txkembali, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txbayar, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clear)))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbberat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(printpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(insert, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txnotransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidpegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txidjenis, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Back >>");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void cbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsearchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        cari = (String)cbsearch.getSelectedItem();
        if(cari == "No Transaksi"){
            search1(jTable1);
        }else if(cari == "ID Pegawai"){
            search2(jTable1);
        }else if(cari == "ID Pelanggan"){
            search3(jTable1);
        }else if(cari == "ID Jenis"){
            search4(jTable1);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src/images/trash.png");
        int dialogButton = JOptionPane.showConfirmDialog (null, "Yakin Ingin Menghapus?","WARNING", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon);
        System.out.println(dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION){
            db.putData("DELETE FROM transaksi WHERE no_transaksi = " + txnotransaksi.getText());

            clear();
            tableload(jTable1);
            kodeload(txnotransaksi);

            JOptionPane.showMessageDialog(null, "Data Deleted");
        }else{
            //remove(dialogButton);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txnotransaksi.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        txidpegawai.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        txidpelanggan.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        txidjenis.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        txtanggal.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
        cbberat.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5)));
        txtotal.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 6)));
        txbayar.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 7)));
        txkembali.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 8)));
        viewStruct();
    }//GEN-LAST:event_jTable1MouseClicked

    private void txidjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidjenisActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        int kembali = 0;
        try {
            String sql = "INSERT INTO transaksi VALUES (?,?,?,?,?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txnotransaksi.getText().trim());
            pst.setString(2, txidpegawai.getText().trim());
            pst.setString(3, txidpelanggan.getText().trim());
            pst.setString(4, txidjenis.getText().trim());
            pst.setDate(5, new java.sql.Date(System.currentTimeMillis()));
            pst.setString(6, cbberat.getSelectedItem().toString());
            pst.setString(7, txtotal.getText().trim());
            pst.setString(8, txbayar.getText().trim());
            kembali = Integer.parseInt(txbayar.getText()) - Integer.parseInt(sumtotal);
            pst.setInt(9, kembali); 
            
            pst.execute();
            
            tableload(jTable1);
            clear();
            kodeload(txnotransaksi);
            JOptionPane.showMessageDialog(null, "Data Saved");
            
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_insertActionPerformed

    private void printpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printpdfActionPerformed
        // TODO add your handling code here:
        try{
            jTextPane1.print();
        }catch(PrinterException e){
            JOptionPane.showMessageDialog(null, "ERROR !!");
            //Logger.getLogger(PrinterSys.class.getName()).log(Level.SEVERE, null, e);
        }
        
        /*
        try {
            // TODO add your handling code here:
            Document doc = new Document(PageSize.A4, 150f, 150f, 0f, 0f);
            try {
                PdfWriter.getInstance(doc, new FileOutputStream("D:\\Education\\FILE KULIAH\\File Belajar Programming\\Programming Java\\Laundry\\Laporan.pdf"));
                JOptionPane.showMessageDialog(null, "PDF Successful Saved to : \nD:\\Education\\FILE KULIAH\\File Belajar Programming\\Programming Java\\Laundry");
            } catch (DocumentException ex) {
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.open();
            doc.add(new Paragraph(jTextPane1.getText().toString()));
            doc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_printpdfActionPerformed

    private void txtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanggalActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        int kembali = Integer.parseInt(txbayar.getText()) - Integer.parseInt(sumtotal);
        try {
            String sql = "UPDATE transaksi SET id_pegawai = "
                + txidpegawai.getText() + ", id_pelanggan = "
                + txidpelanggan.getText() + ", id_jenis = "
                + txidjenis.getText() + ", tanggal = sysdate, berat = "
                + cbberat.getSelectedItem().toString() + ", harga_total = " 
                + txtotal.getText() + ", pembayaran = "
                + txbayar.getText() + ", kembalian = "
                + kembali + " WHERE no_transaksi = "
                + txnotransaksi.getText();
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();

            clear();
            tableload(jTable1);
            kodeload(txnotransaksi);

            JOptionPane.showMessageDialog(null, "Data Updated");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void cbberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbberatActionPerformed
        // TODO add your handling code here:
        total = cbberat.getSelectedItem().toString();
        
        if(total.equals("1")){
            try{
                String sql = "SELECT sum(harga * " + 1 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Salah !!");
            }
        }else if(total.equals("2")){
            try{
                String sql = "SELECT sum(harga * " + 2 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Salah !!");
            }
        }else if(total.equals("3")){
            try{
                String sql = "SELECT sum(harga * " + 3 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Salah !!");
            }
        }else if(total.equals("4")){
            try{
                String sql = "SELECT sum(harga * " + 4 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Salah !!");
            }
        }else if(total.equals("5")){
            try{
                String sql = "SELECT sum(harga * " + 5 + ") FROM jenis_cucian where id_jenis = '" + txidjenis.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rset = pst.executeQuery(sql);
                while (rset.next()){
                    sumtotal = rset.getString(1);
                }
                txtotal.setText(sumtotal);
                txkembali.setText("");
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Salah !!");
            }
        }
       
    }//GEN-LAST:event_cbberatActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        new jenis_cucian().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbberat;
    private javax.swing.JComboBox cbsearch;
    private javax.swing.JButton clear;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton printpdf;
    private javax.swing.JButton search;
    private javax.swing.JTextField txbayar;
    public static javax.swing.JTextField txidjenis;
    private javax.swing.JTextField txidpegawai;
    private javax.swing.JTextField txidpelanggan;
    private javax.swing.JTextField txkembali;
    private javax.swing.JTextField txnotransaksi;
    private javax.swing.JTextField txsearch;
    public static javax.swing.JTextField txtanggal;
    private javax.swing.JTextField txtotal;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    

    private void tableload(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        try { 
            ResultSet rset = db.getData("SELECT * FROM transaksi ORDER BY no_transaksi");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void idpelanggan() {
        String idpel = "";
        try { 
            String sql = "SELECT max(id_pelanggan) FROM pelanggan";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while (rset.next()){
                idpel = rset.getString(1);
            }
            txidpelanggan.setText(idpel);
        } catch (Exception ex) {
            
        }
    }
    
    
    private void kodeload(JTextField jText) {
        try {
            ResultSet rset = db.getData("SELECT max(no_transaksi) FROM transaksi");
            while(rset.next()){
                int i = rset.getInt(1);
                i += 1;
                jText.setText(String.valueOf(i));
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void join(JTable jt){
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        dt.setRowCount(0);
        int total;
        try {
            String sql = "SELECT sum(harga*berat) FROM transaksi, jenis_cucian WHERE transaksi.id_jenis = jenis_cucian.id_jenis";
           // total = 
        } catch (Exception ex) {
            
        }
    }
    
    private void search1(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE no_transaksi LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search2(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_pegawai LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search3(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_pelanggan LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    private void search4(JTable jt2) {
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        dt.setRowCount(0);
        try {
            ResultSet rset = db.getData("SELECT * FROM transaksi WHERE id_jenis LIKE '%" + txsearch.getText() + "%'");
            while(rset.next()){
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));
                v.add(rset.getString(7));
                v.add(rset.getString(8));
                v.add(rset.getString(9));
                dt.addRow(v);
            }
        }catch (Exception ex) {
            
        }
    }
    
    private void clear(){
        kodeload(txnotransaksi);
        txidpegawai.setText("");
        txidpelanggan.setText("");
        txidjenis.setText("");
        txtanggal.setText("System Date");
        cbberat.setSelectedIndex(0);
        txtotal.setText("");
        txbayar.setText("");
        txkembali.setText("");
        txsearch.setText("");
        jTextPane1.setText("");
        
        tableload(jTable1);
    }
    
    private void viewStruct(){
        String jcu = "";
        try { 
            String sql = "SELECT nama_jenis FROM jenis_cucian WHERE id_jenis = " + txidjenis.getText();
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rset = pst.executeQuery(sql);
            while (rset.next()){
                jcu = rset.getString(1);
            }
        } catch (Exception ex) {
            
        }
        jTextPane1.setText(String.valueOf("\t       -- JOSS LAUNDRY -- \n " 
                + "            Jasa Layanan Cuci Kering Setrika Pakaian \n"
                + "         Jl.Semolowaru No.15 | 031-77175735 Surabaya \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n\n  No Transaksi \t : "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 0) + " \n  Tanggal \t\t : "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 4) + " \n  Jenis Cucian \t : "
                + jcu + " \n  Berat Cucian \t : " 
                + jTable1.getValueAt(jTable1.getSelectedRow(), 5) + " \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
                + "\n  Harga Total \t : Rp. "
                + jTable1.getValueAt(jTable1.getSelectedRow(), 6) + " \n"
                + "  Bayar \t\t : Rp. " + jTable1.getValueAt(jTable1.getSelectedRow(), 7) + " \n"
                + " - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -"
                + " \n  *Kembalian \t\t : Rp. " + jTable1.getValueAt(jTable1.getSelectedRow(), 8) + " \n"
        ));
        
    }
    
}
